/*
 * File: app/controller/Cluster.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Cluster', {
    extend: 'Ext.app.Controller',

    stores: [
        'Cluster',
        'Network',
        'Storage'
    ],

    refs: [
        {
            ref: 'grid',
            selector: '#clusterlistgrid'
        }
    ],

    onGridviewItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var window = Ext.widget('clusteradd');

        var form = window.down('form');

        form.loadRecord(record);
    },

    onButtonClickSave: function(button, e, eOpts) {
        var form = button.up('window').down('form');

        var values = form.getValues();
        var store = this.getClusterStore();



        if (form.getForm().isValid()) {
            var record = form.getRecord();

            if (typeof(record) != 'object' ) {
                store.add(values);      
            } else {

                record.set(values);
            }

            button.up('window').close();
        } 
    },

    onButtonClickDelete: function(button, e, eOpts) {
        var selected = this.getGrid().getSelectionModel().getSelection();


        if (selected.length > 0 ) {
            Ext.Msg.confirm('Remove Cluster', 'You are about to remove <span style="color:red;font-weight:bold;">' + selected.length+ '</span> Clusters. Are you sure?', function (button) {
                if (button == 'yes') {
                    this.getClusterStore().remove(selected);
                }
            }, this);

        }
    },

    onGridpanelAfterRender: function(component, eOpts) {
        this.getNetworkStore().load();
        this.getStorageStore().load();
    },

    init: function(application) {
        this.control({
            "#clusterlistgrid": {
                itemdblclick: this.onGridviewItemDblClick
            },
            "clusteradd button[action=save]": {
                click: this.onButtonClickSave
            },
            "#clusterlistdelete": {
                click: this.onButtonClickDelete
            },
            "clusterlist": {
                afterrender: this.onGridpanelAfterRender
            }
        });
    }

});
