/*
 * File: app/controller/Interface.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Interface', {
    extend: 'Ext.app.Controller',

    stores: [
        'Interface'
    ],

    refs: [
        {
            ref: 'grid',
            selector: '#vmeditinterfacegrid'
        }
    ],

    onTabpanelActivate: function(component, eOpts) {
        var store = this.getInterfaceStore();

        store.setVirtualmachineId(this.getController('Virtualmachine').getId());

        store.load();


    },

    onButtonClickSave: function(button, e, eOpts) {
        var form = button.up('window').down('form');

        var values = form.getValues();
        var store = this.getInterfaceStore();



        if (form.getForm().isValid()) {
            var record = form.getRecord();

            if (typeof(record) != 'object' ) {
                console.log(values);
                store.add(values);      
            } else {

                record.set(values);
            }

            button.up('window').close();
        } 
    },

    onGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var window = Ext.widget('interfaceadd');
        var form = window.down('form');

        form.loadRecord(record);
    },

    onButtonClickDelete: function(button, e, eOpts) {


        var selected = this.getGrid().getSelectionModel().getSelection();


        if (selected.length > 0 ) {
            Ext.Msg.confirm('Remove Interface', 'You are about to remove <span style="color:red;font-weight:bold;">' + selected.length+ '</span> Interface. Are you sure?', function (button) {
                if (button == 'yes') {
                    this.getInterfaceStore().remove(selected);
                }
            }, this);

        }
    },

    init: function(application) {
        this.control({
            "#vmeditinterfacetab": {
                activate: this.onTabpanelActivate
            },
            "interfaceadd button[action=save]": {
                click: this.onButtonClickSave
            },
            "#vmeditinterfacegrid": {
                itemdblclick: this.onGridpanelItemDblClick
            },
            "#vmeditinterfacedelete": {
                click: this.onButtonClickDelete
            }
        });
    }

});
