/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Navigation', {
    extend: 'Ext.app.Controller',

    stores: [
        'Navigation',
        'Virtualmachine'
    ],

    refs: [
        {
            ref: 'viewport',
            selector: 'viewport'
        }
    ],

    onTreeviewItemClick: function(dataview, record, item, index, e, eOpts) {
        if (record.get('action') != '') {
            if (record.get('action') == 'vmedit') {        
                var record2 = this.getVirtualmachineStore().findRecord('id', record.get('vmId'));
                this.getController('Virtualmachine').switchVmEdit(record2);
            } else {
                this.switchContent(record.get('action'));
            }
        }
    },

    switchContent: function(name) {
        var viewport = this.getViewport();
        var usersGrid = Ext.widget(name, {region: 'center', id: 'center'});


        viewport.remove('center');
        viewport.add(usersGrid);
        viewport.doLayout();
    },

    onLaunch: function() {
        this.switchContent('vmlist');
    },

    init: function(application) {
        this.control({
            "#Navigation": {
                itemclick: this.onTreeviewItemClick
            }
        });
    }

});
