

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
      "Jan\ZevirtBundle\Entity\User":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_ok, roles: IS_AUTHENTICATED_ANONYMOUSLY }      
        - { path: ^/login_failed, roles: IS_AUTHENTICATED_ANONYMOUSLY } 

        - { path: ^/profile, roles: ROLE_USER } 
        - { path: ^/api/vms, roles: ROLE_USER, methods: [GET] }          
        - { path: ^/api/menus, roles: ROLE_USER, methods: [GET] }          
        - { path: ^/api/jobs, roles: ROLE_USER, methods: [GET] }  
        
        - { path: ^/app, roles: ROLE_USER } 
        
        - { path: ^/, roles: ROLE_ADMIN}  

    

#   service:
#       user_manager: fos_user.user_manager          # Overrides default user manager
#       ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager

    