/*
 * File: app/view/node/List.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.node.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.nodelist',

    height: 250,
    id: '',
    width: 970,
    iconCls: 'icon-node',
    title: 'Nodes',
    store: 'Node',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                id: 'nodelistgrid'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: 'Add Node',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'nodedelete',
                            iconCls: 'icon-delete',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-standby',
                            text: 'Standby',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        id: 'button-standby-on',
                                        iconCls: 'icon-standby-on',
                                        text: 'on'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        id: 'button-standby-off',
                                        iconCls: 'icon-standby-off',
                                        text: 'off'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onGridpanelAfterRender,
                    scope: me
                }
            },
            selModel: Ext.create('Ext.selection.CheckboxModel', {

            }),
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'hostname',
                    text: 'Hostname'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'clusterName',
                    text: 'ClusterName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ha',
                    text: 'Ha'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'corosyncIp1',
                    text: 'CorosyncIp1'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'corosyncIp2',
                    text: 'CorosyncIp2'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'stonith',
                    text: 'Stonith'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'standby',
                    text: 'Standby'
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var windows = Ext.widget('nodeadd');
    },

    onGridpanelAfterRender: function(component, eOpts) {
        var Mask = new Ext.LoadMask(this.getEl(), {"msg":"Please wait..", "store": this.getStore()});
        Mask.show();
        this.getStore().load();

    }

});