/*
 * File: app/view/disk/menu/Drbd.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.disk.menu.Drbd', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.diskmenudrbd',

    width: 120,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    text: 'remove DRBD'
                },
                {
                    xtype: 'menuitem',
                    text: 'Set Primary'
                }
            ]
        });

        me.callParent(arguments);
    }

});