/*
 * File: app/model/Disk.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Disk', {
    extend: 'Ext.data.Model',

    idProperty: 'id',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'entity'
        },
        {
            name: 'name'
        },
        {
            name: 'path'
        },
        {
            name: 'storage'
        },
        {
            name: 'volume'
        },
        {
            name: 'driverType'
        },
        {
            name: 'diskDevice'
        },
        {
            name: 'action'
        },
        {
            name: 'filename'
        },
        {
            name: 'size'
        },
        {
            name: 'capacity'
        },
        {
            name: 'allocation'
        },
        {
            name: 'node'
        },
        {
            name: 'nodeA'
        },
        {
            name: 'nodeB'
        },
        {
            name: 'ipA'
        },
        {
            name: 'ipB'
        },
        {
            name: 'diskA'
        },
        {
            name: 'storageName'
        },
        {
            name: 'virtualmachineId'
        }
    ]
});