/*
 * File: app/view/explorer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.explorer', {
    extend: 'Ext.window.Window',
    alias: 'widget.explorer',

    autoShow: true,
    height: 250,
    width: 400,
    autoScroll: true,
    title: 'Explorer',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    border: false,
                    minHeight: 100,
                    store: 'File',
                    rootVisible: false,
                    viewConfig: {

                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});