/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'MyApp.view.MainView',
    renderTo: Ext.getBody(),
    requires: [
        'MyApp.view.MainView',
        'MyApp.view.vm.List',
        'MyApp.view.vm.Add',
        'MyApp.view.vm.contextmenu',
        'MyApp.view.vm.Edit',
        'MyApp.view.storage.List',
        'MyApp.view.storage.Dir',
        'MyApp.view.storage.Iscsi',
        'MyApp.view.storage.Netfs',
        'MyApp.view.storage.Rbd',
        'MyApp.view.storage.Logical',
        'MyApp.view.node.List',
        'MyApp.view.node.Add',
        'MyApp.view.vm.Vnc',
        'MyApp.view.disk.Existing',
        'MyApp.view.explorer',
        'MyApp.view.disk.Add',
        'MyApp.view.storage.disk.List',
        'MyApp.view.cluster.List',
        'MyApp.view.cluster.Add',
        'MyApp.view.network.List',
        'MyApp.view.network.Add',
        'MyApp.view.interface.Add',
        'MyApp.view.disk.Drbd',
        'MyApp.view.disk.Menu',
        'MyApp.view.disk.menu.Drbd',
        'MyApp.view.disk.Edit',
        'MyApp.view.job.Detail',
        'MyApp.view.user.List',
        'MyApp.view.user.Add',
        'MyApp.view.template.List',
        'MyApp.view.vm.edit.disk.List'
    ]
});