/*
 * File: app/view/storage/Iscsi.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.storage.Iscsi', {
    extend: 'Ext.window.Window',
    alias: 'widget.storageiscsi',

    autoShow: true,
    border: false,
    height: 168,
    width: 380,
    layout: {
        type: 'fit'
    },
    title: 'Storage ISCSI',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: 'Save',
                    action: 'save'
                },
                {
                    text: 'Cancel',
                    scope: this,
                    handler: this.close
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'name',
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'hostname',
                            fieldLabel: 'Hostname'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'devicePath',
                            fieldLabel: 'Identifier'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'entity',
                            value: 'StorageIscsi',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});