/*
 * File: app/view/disk/Drbd.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.disk.Drbd', {
    extend: 'Ext.window.Window',
    alias: 'widget.diskdrbd',

    autoShow: true,
    border: false,
    height: 282,
    width: 410,
    layout: {
        type: 'fit'
    },
    bodyPadding: 0,
    title: 'Drbd',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: 'Save',
                    action: 'save'
                },
                {
                    text: 'Cancel',
                    scope: this,
                    handler: this.close
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'diskDrbdNodeA',
                            fieldLabel: 'Node A',
                            labelWidth: 150,
                            name: 'nodeA',
                            readOnly: true,
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'Node',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            displayTpl: '<tpl for=".">{interfaceName} - {ip}</tpl>',
                            tpl: '<tpl for="."><div class="x-boundlist-item">{interfaceName} - {ip}</div></tpl>',
                            anchor: '100%',
                            id: 'diskDrbdIpA',
                            fieldLabel: 'Node A Interface',
                            labelWidth: 150,
                            name: 'ipA',
                            displayField: 'interfaceName',
                            queryMode: 'local',
                            store: 'IpA',
                            valueField: 'ip'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'diskDrbdNodeB',
                            fieldLabel: 'Node B',
                            labelWidth: 150,
                            name: 'nodeB',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'Node',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            displayTpl: '<tpl for=".">{interfaceName} - {ip}</tpl>',
                            tpl: '<tpl for="."><div class="x-boundlist-item">{interfaceName} - {ip}</div></tpl>',
                            anchor: '100%',
                            id: 'diskDrbdIpB',
                            fieldLabel: 'Node B Interface',
                            labelWidth: 150,
                            name: 'ipB',
                            displayField: 'interfaceName',
                            queryMode: 'local',
                            store: 'IpB',
                            valueField: 'ip'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: '',
                            fieldLabel: 'Storage',
                            labelWidth: 150,
                            name: 'storage',
                            displayField: 'name',
                            store: 'Storage',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'diskaddsize',
                            fieldLabel: 'Size in GB',
                            labelWidth: 150,
                            name: 'capacity'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Disk Device',
                            labelWidth: 150,
                            name: 'diskDevice',
                            displayField: 'name',
                            store: 'disk.Device',
                            valueField: 'name'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'action',
                            value: 'drbd'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'diskDrbdDiskA',
                            fieldLabel: 'Label',
                            name: 'diskA'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});