/*
 * File: app/view/disk/Edit.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.disk.Edit', {
    extend: 'Ext.window.Window',
    alias: 'widget.diskedit',

    autoShow: true,
    height: 132,
    width: 400,
    layout: {
        type: 'fit'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: 'Save',
                    action: 'save'
                },
                {
                    text: 'Cancel',
                    scope: this,
                    handler: this.close
                }
            ],
            items: [
                {
                    xtype: 'form',
                    border: false,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Driver Type',
                            name: 'driverType',
                            displayField: 'name',
                            store: 'disk.driver.Type',
                            valueField: 'name'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Disk Device',
                            name: 'diskDevice',
                            displayField: 'name',
                            store: 'disk.Device',
                            valueField: 'name'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});