/*
 * File: app/view/disk/Existing.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.disk.Existing', {
    extend: 'Ext.window.Window',
    alias: 'widget.diskexisting',

    autoShow: true,
    border: false,
    height: 200,
    width: 444,
    layout: {
        type: 'fit'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: 'Save',
                    action: 'save'
                },
                {
                    text: 'Cancel',
                    scope: this,
                    handler: this.close
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            name: 'diskType',
                            fieldLabel: 'Disk Type',
                            displayField: 'name',
                            store: 'disk.Type',
                            valueField: 'name'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            name: 'driverType',
                            fieldLabel: 'Driver Type',
                            displayField: 'name',
                            store: 'disk.driver.Type',
                            valueField: 'name'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            name: 'diskDevice',
                            fieldLabel: 'Disk Device',
                            displayField: 'name',
                            store: 'disk.Device',
                            valueField: 'name'
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'pathField',
                                    width: 300,
                                    name: 'path',
                                    fieldLabel: 'Path'
                                },
                                {
                                    xtype: 'button',
                                    id: 'exploreropen',
                                    style: 'margin-left:10px;',
                                    text: 'File Explorer'
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'action',
                            value: 'other',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});