/*
 * File: app/store/Events.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Events', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Event'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,
            model: 'MyApp.model.Event',
            storeId: 'MyJsonStore14',
            proxy: {
                type: 'rest',
                url: '/api/events',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    },

    setLastEvent: function() {
        this.getProxy().url = '/api/events/last';

    },

    setEvent: function(id) {
        this.getProxy().url = '/api/events?id='+id;

    }

});