/*
 * File: app/store/Interface.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Interface', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Interface'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoSync: true,
            storeId: 'MyJsonStore7',
            model: 'MyApp.model.Interface',
            proxy: {
                type: 'rest',
                url: '/api/vms/1/interfaces',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    },

    setVirtualmachineId: function(vm) {
        this.getProxy().url = '/api/vms/' + vm + '/interfaces';
    }

});