/*
 * File: app/store/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Navigation', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.Navigation'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'MyJsonTreeStore',
            model: 'MyApp.model.Navigation',
            proxy: {
                type: 'rest',
                url: '/api/menus',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});