/*
 * File: app/store/Node.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Node', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Node'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,
            storeId: 'MyJsonStore2',
            model: 'MyApp.model.Node',
            proxy: {
                type: 'rest',
                url: '/api/nodes',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    },

    loadDrbdNodes: function(vmId) {
        var old = this.getProxy().url;

        this.getProxy().url = '/api/nodes/' + vmId + '/drbd';

        this.load();

        this.getProxy().url = old;
    }

});