/*
 * File: app/store/StonithMeta.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.StonithMeta', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.StonithMeta'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore13',
            model: 'MyApp.model.StonithMeta',
            proxy: {
                type: 'rest',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    },

    setNodeAndStonith: function(node, stonith) {

        this.getProxy().url = '/api/nodes/'+node+'/stoniths/'+stonith.replace(/\//,'|')+'/metas';

    }

});