/*
 * File: app/view/vm/Vnc.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.vm.Vnc', {
    extend: 'Ext.window.Window',
    alias: 'widget.vmvnc',

    width: 1024,
    layout: {
        type: 'fit'
    },
    title: 'VNC',
    constrain: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    autoEl: {
                        tag: 'iframe',
                        src: '',
                        style: 'border:0px;'
                    },
                    id: 'vnciframe'
                }
            ]
        });

        me.callParent(arguments);
    }

});